"""
Shared schemas used across the RAG system.

Includes Task, PlannerOutput, BranchResult, and BranchError.
Following ARCHITECTURE.md Section 5.2 and 4.4.
"""

from pydantic import BaseModel, Field
from typing import Literal


# ============================================================================
# Type Definitions
# ============================================================================

DataType = Literal["type1", "type2", "type3"]
"""
Data source types:
- type1: SQL/structured data
- type2: Vector search
- type3: Graph/knowledge graph
"""

BranchStatus = Literal["none", "running", "success", "failed"]
"""
Branch execution status:
- none: Not started
- running: In progress
- success: Completed successfully
- failed: Failed after retries
"""


# ============================================================================
# Task Schema (From Planner)
# ============================================================================

class Task(BaseModel):
    """
    A task in the DAG generated by planner.
    
    Each task represents a unit of work to be executed by a subgraph.
    """
    
    task_id: str = Field(
        ...,
        description="Unique ID within a planning iteration (e.g. task_1, task_2)"
    )
    
    data_type: DataType = Field(
        ...,
        description="Data source type: type1 (SQL), type2 (Vector), type3 (Graph)"
    )
    
    query: str = Field(
        ...,
        description="Optimized sub-query for this data source"
    )
    
    parameters: dict = Field(
        default_factory=dict,
        description="Additional parameters: date_from, date_to, customer_id, etc."
    )
    
    depends_on: list[str] = Field(
        default_factory=list,
        description="List of task_ids that must complete before this task (DAG edges)"
    )


# ============================================================================
# Planner Output Schema
# ============================================================================

class PlannerOutput(BaseModel):
    """
    Output from planner node.
    
    This is unpacked into MainState - not stored directly.
    """
    
    is_finished: bool = Field(
        ...,
        description="True if enough information to answer the question"
    )
    
    reasoning: str = Field(
        default="",
        description="Explanation of why finished or need more tasks"
    )
    
    tasks: list[Task] = Field(
        default_factory=list,
        description="Tasks to execute. Empty if is_finished=True"
    )


# ============================================================================
# Branch Result Schema
# ============================================================================

class BranchResult(BaseModel):
    """
    Result from a branch/subgraph after completion.
    
    Accumulated in MainState.branch_results via reducer.
    """
    
    task_id: str = Field(..., description="ID of the completed task")
    
    data_type: DataType = Field(..., description="Data source type")
    
    status: BranchStatus = Field(..., description="Final execution status")
    
    content: str = Field(
        default="",
        description="Result content to merge into final answer"
    )
    
    latency: float = Field(
        default=0.0,
        description="Execution time in seconds"
    )
    
    token_usage: int = Field(
        default=0,
        description="Total LLM tokens used in this branch"
    )


# ============================================================================
# Branch Error Schema
# ============================================================================

class BranchError(BaseModel):
    """
    Error from a branch that exceeded max retries.
    
    Accumulated in MainState.errors via reducer.
    """
    
    task_id: str = Field(..., description="ID of the failed task")
    
    data_type: DataType = Field(..., description="Data source type")
    
    error_message: str = Field(..., description="Error description")
    
    retry_count: int = Field(
        default=0,
        description="Number of retries attempted"
    )
