"""
Shared schemas used across the RAG system.

Includes Task, PlannerOutput, BranchResult, and BranchError.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


# ============================================================================
# Type Definitions
# ============================================================================

DataType = Literal["type1", "type2", "type3"]
"""
Data source types:
- type1: Vector/document search (RAG)
- type2: Reserved for future use
- type3: Reserved for future use
"""

TaskStatus = Literal["pending", "running", "success", "failed", "exhausted"]
"""
Task execution status:
- pending:   Not started yet
- running:   Currently executing in a subgraph
- success:   Completed successfully
- failed:    Failed but can still retry (retry_count < MAX_RETRY)
- exhausted: Failed and exceeded MAX_RETRY — will not retry
"""

BranchStatus = Literal["none", "running", "success", "failed"]
"""Branch execution status (subset used in BranchResult)."""

MAX_TASK_RETRY: int = 3
"""Maximum number of retries per task before marking as exhausted."""

MAX_PARALLEL_TASKS: int = 3
"""Maximum number of tasks dispatched in parallel per iteration."""


# ============================================================================
# Task Schema (From Planner)
# ============================================================================

class Task(BaseModel):
    """
    A task in the plan generated by the planner.

    Each task represents one unit of retrieval work routed to a subgraph.
    Tasks with depends_on=[...] must wait until dependencies are done.
    """

    task_id: str = Field(
        ...,
        description="Unique ID within a planning iteration (e.g. task_1, task_2)",
    )

    data_type: DataType = Field(
        ...,
        description="Data source type determining which subgraph handles this task",
    )

    query: str = Field(
        ...,
        description="Optimized sub-query for this specific data source",
    )

    parameters: dict = Field(
        default_factory=dict,
        description="Additional parameters passed to the subgraph (top_k, filters, etc.)",
    )

    depends_on: list[str] = Field(
        default_factory=list,
        description="task_ids that must complete before this task can run",
    )

    status: TaskStatus = Field(
        default="pending",
        description="Current execution status of this task",
    )

    retry_count: int = Field(
        default=0,
        description=f"Number of retries attempted. When >= {MAX_TASK_RETRY}, status -> exhausted",
    )

    # ── Helpers ─────────────────────────────────────────────────────────────

    def is_done(self) -> bool:
        """True if this task no longer needs execution."""
        return self.status in ("success", "exhausted")

    def can_retry(self) -> bool:
        """True if this task failed but still has retries left."""
        return self.status == "failed" and self.retry_count < MAX_TASK_RETRY

    def mark_running(self) -> "Task":
        return self.model_copy(update={"status": "running"})

    def mark_success(self) -> "Task":
        return self.model_copy(update={"status": "success"})

    def mark_failed(self) -> "Task":
        new_count = self.retry_count + 1
        new_status: TaskStatus = (
            "exhausted" if new_count >= MAX_TASK_RETRY else "failed"
        )
        return self.model_copy(update={"status": new_status, "retry_count": new_count})


# ============================================================================
# Planner Output Schemas
# ============================================================================

class PlannerPlanOutput(BaseModel):
    """
    Structured output from Planner Chain 1 (planning chain).

    Used with .with_structured_output() — LLM fills this directly.
    Temperature = 0, strong model.
    """

    reasoning: str = Field(
        ...,
        description="Step-by-step analysis of what information is needed",
    )

    tasks: list[Task] = Field(
        default_factory=list,
        description=(
            "List of retrieval tasks to dispatch. "
            "Each task targets one data source. "
            "Empty list means no retrieval needed."
        ),
    )


class PlannerDecisionOutput(BaseModel):
    """
    Structured output from Planner Chain 2 (decision/replan chain).

    Runs after merge to decide: continue or finish.
    Temperature = 0, middle model.
    """

    is_finished: bool = Field(
        ...,
        description=(
            "True if there is enough information to answer the user query. "
            "True also when all remaining tasks are exhausted (no more retries)."
        ),
    )

    reasoning: str = Field(
        ...,
        description="Explanation for why we are finished or why we need more tasks",
    )

    new_tasks: list[Task] = Field(
        default_factory=list,
        description=(
            "Additional tasks to run if is_finished=False. "
            "These are appended to the task list for the next iteration."
        ),
    )


# ============================================================================
# Branch Result Schema
# ============================================================================

class BranchResult(BaseModel):
    """
    Result emitted by a subgraph after it finishes executing a task.

    Accumulated in MainState.branch_results via the `add` reducer.
    """

    task_id: str = Field(..., description="ID of the completed task")

    data_type: DataType = Field(..., description="Data source type that produced this result")

    status: BranchStatus = Field(..., description="Final execution status")

    content: str = Field(
        default="",
        description="Retrieved and formatted content to be used by synthesizer",
    )

    source_metadata: list[dict] = Field(
        default_factory=list,
        description="List of source metadata dicts (chunk_id, document_id, section, score, etc.)",
    )

    latency: float = Field(default=0.0, description="Execution time in seconds")

    token_usage: int = Field(default=0, description="Total LLM tokens used in this branch")


# ============================================================================
# Branch Error Schema
# ============================================================================

class BranchError(BaseModel):
    """
    Error record for a branch that exceeded MAX_TASK_RETRY.

    Accumulated in MainState.errors via the `add` reducer.
    """

    task_id: str = Field(..., description="ID of the failed task")

    data_type: DataType = Field(..., description="Data source type")

    error_message: str = Field(..., description="Last error description")

    retry_count: int = Field(default=0, description="Number of retries attempted")
